"""add order delivery fields

Revision ID: fe3175f99532
Revises: 7e1586fc37aa
Create Date: 2026-06-23 00:58:15.555421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe3175f99532'
down_revision: Union[str, Sequence[str], None] = '7e1586fc37aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_method', sa.String(length=30), nullable=False))
    op.add_column('orders', sa.Column('payment_method', sa.String(length=30), nullable=False))
    op.add_column('orders', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'note')
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'shipping_method')
    # ### end Alembic commands ###
